import { execFileSync, spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, readdirSync, readFileSync, statSync, unlinkSync, writeFileSync } from "node:fs";
import path from "node:path";
import { Client } from "pg";

const composeProject = "dugnadapp-shared";
const generatedHeader = "# Generated by dugnadapp agent bootstrap";
const prismaCommand = path.join(
  process.cwd(),
  "node_modules",
  ".bin",
  process.platform === "win32" ? "prisma.cmd" : "prisma",
);
const nextCommand = path.join(
  process.cwd(),
  "node_modules",
  ".bin",
  process.platform === "win32" ? "next.cmd" : "next",
);

function runCapture(command: string, args: string[]) {
  return execFileSync(command, args, {
    cwd: process.cwd(),
    encoding: "utf8",
    stdio: ["pipe", "pipe", "pipe"],
  }).trim();
}

function run(command: string, args: string[]) {
  const result = spawnSync(command, args, {
    cwd: process.cwd(),
    stdio: "inherit",
    shell: process.platform === "win32",
  });

  if (result.error) {
    throw result.error;
  }

  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

function sanitizeIdentifier(value: string) {
  const sanitized = value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .replace(/_+/g, "_");

  return sanitized || "agent";
}

function limitIdentifier(value: string, maxLength = 63) {
  return value.slice(0, maxLength).replace(/_+$/g, "");
}

function parseEnvFile(filePath: string) {
  const entries = readFileSync(filePath, "utf8")
    .split(/\r?\n/)
    .filter((line) => line.trim() && !line.trim().startsWith("#"))
    .map((line) => {
      const separatorIndex = line.indexOf("=");

      if (separatorIndex === -1) {
        return null;
      }

      const key = line.slice(0, separatorIndex).trim();
      const rawValue = line.slice(separatorIndex + 1).trim();
      const value =
        rawValue.startsWith("\"") && rawValue.endsWith("\"")
          ? rawValue.slice(1, -1)
          : rawValue;

      return [key, value] as const;
    })
    .filter((entry): entry is readonly [string, string] => entry !== null);

  return Object.fromEntries(entries);
}

function getAdminUrl() {
  return process.env.DATABASE_ADMIN_URL ?? "postgresql://postgres:postgres@localhost:5432/postgres";
}

function buildDatabaseUrl(adminUrl: string, databaseName: string) {
  const url = new URL(adminUrl);
  url.pathname = `/${databaseName}`;
  url.searchParams.set("schema", "public");

  return url.toString();
}

function resolveAgentConfig() {
  const repoRoot = runCapture("git", ["rev-parse", "--show-toplevel"]);
  const branch = sanitizeIdentifier(runCapture("git", ["rev-parse", "--abbrev-ref", "HEAD"]));
  const worktreeName = sanitizeIdentifier(path.basename(repoRoot));
  const hash = createHash("sha1").update(repoRoot).digest("hex").slice(0, 8);
  const port = 3100 + (Number.parseInt(hash.slice(0, 4), 16) % 400);
  const agentId = limitIdentifier(`${worktreeName}_${branch}_${hash}`, 50);
  const databaseName = limitIdentifier(`dugnadapp_${worktreeName}_${hash}`);
  const shadowDatabaseName = limitIdentifier(`dugnadapp_shadow_${worktreeName}_${hash}`);
  const adminUrl = getAdminUrl();

  return {
    agentId,
    adminUrl,
    branch,
    databaseName,
    envPath: path.join(repoRoot, ".env"),
    port,
    repoRoot,
    shadowDatabaseName,
    worktreeName,
  };
}

function buildEnvContent(config: ReturnType<typeof resolveAgentConfig>) {
  const databaseUrl = buildDatabaseUrl(config.adminUrl, config.databaseName);
  const shadowDatabaseUrl = buildDatabaseUrl(config.adminUrl, config.shadowDatabaseName);

  return [
    generatedHeader,
    `# Worktree: ${config.worktreeName}`,
    `# Branch: ${config.branch}`,
    `AGENT_ID="${config.agentId}"`,
    `DATABASE_ADMIN_URL="${config.adminUrl}"`,
    `DATABASE_URL="${databaseUrl}"`,
    `SHADOW_DATABASE_URL="${shadowDatabaseUrl}"`,
    `PORT="${config.port}"`,
    `AGENT_DB_NAME="${config.databaseName}"`,
    `AGENT_SHADOW_DB_NAME="${config.shadowDatabaseName}"`,
    "",
  ].join("\n");
}

function writeEnvFile(config: ReturnType<typeof resolveAgentConfig>, force: boolean) {
  if (existsSync(config.envPath)) {
    const current = readFileSync(config.envPath, "utf8");

    if (!current.startsWith(generatedHeader) && !force) {
      throw new Error(
        `Refusing to overwrite unmanaged .env at ${config.envPath}. Re-run with --force if that is intentional.`,
      );
    }
  }

  writeFileSync(config.envPath, buildEnvContent(config), "utf8");
}

function dockerComposeArgs(args: string[]) {
  return ["compose", "-p", composeProject, ...args];
}

async function queryAdmin(adminUrl: string, sql: string) {
  const client = new Client({
    connectionString: adminUrl,
  });

  await client.connect();

  try {
    return await client.query(sql);
  } finally {
    await client.end();
  }
}

async function adminDatabaseReachable(adminUrl: string) {
  try {
    await queryAdmin(adminUrl, "SELECT 1");
    return true;
  } catch {
    return false;
  }
}

async function ensureServerRunning(adminUrl: string) {
  if (await adminDatabaseReachable(adminUrl)) {
    return;
  }

  run("docker", dockerComposeArgs(["up", "-d", "db"]));
}

async function waitForServerReady(adminUrl: string) {
  for (let attempt = 0; attempt < 30; attempt += 1) {
    if (await adminDatabaseReachable(adminUrl)) {
      return;
    }

    await new Promise((resolve) => setTimeout(resolve, 1000));
  }

  throw new Error("Postgres did not become ready in time.");
}

async function execAdminSql(adminUrl: string, sql: string) {
  await queryAdmin(adminUrl, sql);
}

async function databaseExists(adminUrl: string, name: string) {
  const result = await queryAdmin(
    adminUrl,
    `SELECT 1 FROM pg_database WHERE datname = '${name}'`,
  );

  return (result.rowCount ?? 0) > 0;
}

async function ensureDatabase(adminUrl: string, name: string) {
  if (!(await databaseExists(adminUrl, name))) {
    await execAdminSql(adminUrl, `CREATE DATABASE "${name}";`);
  }
}

async function dropDatabase(adminUrl: string, name: string) {
  if (!(await databaseExists(adminUrl, name))) {
    return;
  }

  await execAdminSql(
    adminUrl,
    `SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = '${name}' AND pid <> pg_backend_pid();`,
  );
  await execAdminSql(adminUrl, `DROP DATABASE IF EXISTS "${name}";`);
}

function hasCommittedMigrations(repoRoot: string) {
  const migrationsPath = path.join(repoRoot, "prisma", "migrations");

  if (!existsSync(migrationsPath)) {
    return false;
  }

  return readdirSync(migrationsPath).some((entry) => {
    const fullPath = path.join(migrationsPath, entry);
    return statSync(fullPath).isDirectory();
  });
}

function runPrisma(args: string[]) {
  run(prismaCommand, args);
}

function loadExistingConfig() {
  const config = resolveAgentConfig();

  if (!existsSync(config.envPath)) {
    throw new Error("Missing .env for this worktree. Run `npm run agent:init` first.");
  }

  const env = parseEnvFile(config.envPath);

  return {
    ...config,
    databaseName: env.AGENT_DB_NAME ?? config.databaseName,
    port: env.PORT ? Number.parseInt(env.PORT, 10) : config.port,
    shadowDatabaseName: env.AGENT_SHADOW_DB_NAME ?? config.shadowDatabaseName,
  };
}

async function init(flags: Set<string>) {
  const config = resolveAgentConfig();

  await ensureServerRunning(config.adminUrl);
  await waitForServerReady(config.adminUrl);
  writeEnvFile(config, flags.has("--force"));
  await ensureDatabase(config.adminUrl, config.databaseName);
  await ensureDatabase(config.adminUrl, config.shadowDatabaseName);

  if (hasCommittedMigrations(config.repoRoot)) {
    runPrisma(["migrate", "deploy"]);
  } else {
    runPrisma(["db", "push", "--skip-generate"]);
  }

  if (flags.has("--seed")) {
    runPrisma(["db", "seed"]);
  }
}

async function destroy() {
  const config = loadExistingConfig();

  await ensureServerRunning(config.adminUrl);
  await waitForServerReady(config.adminUrl);
  await dropDatabase(config.adminUrl, config.shadowDatabaseName);
  await dropDatabase(config.adminUrl, config.databaseName);

  if (existsSync(config.envPath)) {
    const current = readFileSync(config.envPath, "utf8");

    if (current.startsWith(generatedHeader)) {
      unlinkSync(config.envPath);
    }
  }
}

async function dev() {
  const config = loadExistingConfig();
  await ensureServerRunning(config.adminUrl);
  run(nextCommand, ["dev", "--port", String(config.port)]);
}

function info() {
  const config = existsSync(path.join(process.cwd(), ".env")) ? loadExistingConfig() : resolveAgentConfig();
  process.stdout.write(`${buildEnvContent(config)}\n`);
}

async function main() {
  const [command, ...rest] = process.argv.slice(2);
  const flags = new Set(rest);

  switch (command) {
    case "init":
      await init(flags);
      break;
    case "destroy":
      await destroy();
      break;
    case "dev":
      await dev();
      break;
    case "info":
      info();
      break;
    default:
      throw new Error("Use one of: init, destroy, dev, info.");
  }
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
